### ISSUE TITLE
chromuim browsers returns M1 as `macIntel` platform & useragent

### ISSUE THREAD

**Issue by Bad3r** [logseq/sites#15]
https://stackoverflow.com/questions/64853342/whats-the-value-of-navigator-platform-on-arm-macs

https://user-images.githubusercontent.com/25513724/216495699-2de90760-620f-4e1e-8da5-9f137594ebf1.mov

**Comment by thibaultmol** [comment]
Was about to make an issue about this as well.
My chromebook is detected as a macbook on the new site.
My useragent is:
[Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)

**Comment by thibaultmol** [comment]
Has this been pushed to the site yet? (chromebooks are still showing macos download instead of linux)
