### ISSUE TITLE
Potential redundancy of cookie banner

### ISSUE THREAD

**Issue by sawhney17** [logseq/sites#4]
<img width="1140" alt="Screenshot 2023-01-04 at 9 37 33 PM" src="https://user-images.githubusercontent.com/80150109/210616003-1f7e5b68-892d-43fe-bbc8-851c5dd2e6c7.png">

From this comment, it appears that a cookie banner is redundant.

**Comment by alxlg** [comment]
To be precise it is not mandatory.

The only thing you need for the whole Logseq project is the user checking "I've read terms of service" (that include the privacy policy) when registering to use Sync or other services that require registration.

For a landing page that is only using technical cookies there is no need for a cookie agreement popup. As I said, that it is needed when profiling/tracking people that visit your site.

For those who don't know, cookies agreement are required by some European countries as a measure to let people browsing the Web that some pages could profile/track them.

**Comment by xyhp915** [comment]
@sawhney17 @alxlg Thanks for these details. Currently, it's redundant for sure!
